name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Mise à jour vers la dernière version

      - name: Install, build, and upload site
        uses: withastro/action@v1

      - name: Upload build artifact
        uses: actions/upload-artifact@v4  # Mise à jour vers la dernière version
        with:
          name: astro-build
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4  # Ajout de l'étape pour récupérer les fichiers avant le déploiement
        with:
          name: astro-build
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
